### ISSUE TITLE
Move some of README.md content to wiki

### ISSUE THREAD

**Issue by Lithium95** [PalisadoesFoundation/infoset-ng#1]
The content on the readme is really extensive and daunting, it would better suited in the project's github wiki.

**Comment by palisadoes** [comment]
What would you suggest to move?

**Comment by Lithium95** [comment]
Everything from the table of content down. The way how wikis on Github work, you could have the table of content as a side-menu and have the details on different pages so it's more easy on the eyes.

**Comment by Pr0x1m4** [comment]
Nice suggestion, README is a bit daunting, a lot of info there would be suited for the project's wiki. 

Or we could just remove the content and add a link to [Original Wiki](http://wiki.palisadoes.org/index.php/Infoset) to the README.md (for anyone who wants to), considering that the content there is dated and need updating.

README.md should really be install/build instructions.

**Comment by palisadoes** [comment]
I'd much rather have the documentation as part of the code base possibly as a `docs/` directory. This way it will always be easy to update rather on a separate wiki. I've noticed Gunicorn does this. For example http://docs.gunicorn.org/en/stable/settings.html has a link in the top right hand corner to the GitHub docs/source/ directory which is visible at: https://github.com/benoitc/gunicorn/blob/4a04195975563d2f4ec28ffaa70d138beda76da4/docs/source/settings.rst

Is this something the GitHub wiki can facilitate?

**Comment by palisadoes** [comment]
This has been fixed in the latest pull request.
