### ISSUE TITLE
Create a React-based web frontend to manage infoset-ng's configuration

### ISSUE THREAD

**Issue by chenshuiluke** [PalisadoesFoundation/infoset-ng#127]
### Steps to Reproduce:
N/A
### Issue Type:
Feature
### Details
Currently, infoset's configuration can only be changed by modifying the required YAML files. This is unnecessarily complicated, so the proposed solution is to create a frontend for the configuration using ReactJS. 

This configuration page will probably be served from a `/config` route and will have different sections for each configuration file, to keep things organized. There should be different input options available for the various settings. For example, a textbox may be appropriate for a database username setting, but a simple checkbox would be more appropriate for a setting that only accepts true/false values. 

To make things easier, a simple markdown document that outlines the config files, settings in the config files and the acceptable input types for each setting should be created for easy reference while this configuration page is made. Something like this would be acceptable:

# Configuration Details
### Settings:

- random-setting: text input
- another-setting: numeric input
- somethingelse-setting: true/false
- list-setting: ["daemon mode", "one time mode", "something else mode"]

**Comment by Pr0x1m4** [comment]
The settings page should include all options in the yaml file [config file](https://github.com/PalisadoesFoundation/infoset-ng/blob/master/examples/etc/config.yaml)

**Comment by Pr0x1m4** [comment]
Fixed #138
