### ISSUE TITLE
Investigate the possibility of switching from MySQL to SQLite

### ISSUE THREAD

**Issue by chenshuiluke** [PalisadoesFoundation/infoset-ng#141]
# Feature Request

I think we should investigate the possibility of using SQLite instead of MySQL due to the small amount of required database features infoset needs.

### Context

Currently, people who want to install infoset need to install MySQL as well, which only adds to an already complicated installation process. 

## Possible advantages of using SQLite

- Easier installation process. An SQLite db is a simple db file as stated [here](https://docs.python.org/3/library/sqlite3.html)

- Easier migration of data. In the event that you need to migrate your infoset installation, you wouldn't have to go through the process of migrating your mysql data. You'd only need to copy the `.db` file.

- Easier configuration. Currently, there are multiple configuration settings related only to database configuration, namely  `db_hostname`, `db_name`, `db_password` and `db_username`. Using SQLite, you'd only need to know the name/location of the db file.

You can find out more information about it [here](https://www.sqlite.org/whentouse.html)

**Comment by Pr0x1m4** [comment]
Great suggestion, this would make a great addition to `infoset-ng`. For further reading, here's an article for some use cases of SQLite `http://www.sqlite.org/whentouse.html`

**Comment by chenshuiluke** [comment]
Currently working on switching to SQLite. I changed the engine like [here](http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlite), but I'm currently getting an exception:

    (sqlite3.OperationalError) no such table: iset_agent [SQL: 'SELECT iset_agent.id_agent AS 
    iset_agent_id_agent \nFROM iset_agent \nWHERE iset_agent.id_agent = ? 
    AND iset_agent.idx_agent = ?'] [parameters: (<memory at 0x7feb520aab88>, -1)]

is there some sort of db model initialization code that might need to be checked?
