### ISSUE TITLE
Infoset API Agent doesn't reload new settings

### ISSUE THREAD

**Issue by Pr0x1m4** [PalisadoesFoundation/infoset-ng#65]
On starting `bin/infoset-ng-api` with the `--start` option, the daemon runs fine. But a change in the settings file `infoset-ng/etc/config.yml`, followed by the command `bin/infoset-ng-api` with the `--restart` option shows that daemon is still running with the previous config values.

Problem seems to stem from gunicorn's masterpid
Background: http://blog.tplus1.com/blog/2010/12/31/how-to-restart-a-gunicorn-server-from-vim/

Steps to Re-create: 

1. Run `./bin/infoset-ng-api --start`
2. Change value in config.yml eg.`listen_address`
3. Run `./bin/infoset-ng-api --restart`

I suspect the same problem exists in with garnet's daemons as well, Needs investigation

**Comment by Pr0x1m4** [comment]
We might just need to put an advisory warning in the docs.

To date, the following does work and settings are reloaded

1. Run `./bin/infoset-ng-api --start`
2. Change value in config.yml eg `listen_address`
3. Run `./bin/infoset-ng-api --stop`
4. Then Run `./bin/infoset/ng-api --start`

**Comment by palisadoes** [comment]
It works as expected when no git pulls are done. It seems to fail when you switch branches or do a git pull. I've seen issues where python daemons become unresponsive after doing these. 

Try all three scenarios and let me know if that's the issue.

**Comment by palisadoes** [comment]
I've reproduced the issue. Found a fix. Creating a pull request soon.

**Comment by palisadoes** [comment]
The fix is in bin/infoset-ng-api (references to Gunicorn) You may want to do the same for Garnet
